// AILrc/frontend/src/App.tsx
import { useState, useEffect, useRef, useLayoutEffect, useMemo, useCallback } from 'react';
import { SetWindowClickThrough, QuitApp, ResizeWindow } from "../wailsjs/go/main/App";
import { EventsOn } from "../wailsjs/runtime/runtime";
import { useAimp } from './hooks/useAimp';
import { useLyrics } from './hooks/useLyrics';
import { useConfig } from './hooks/useConfig';
import { ControlBar } from './components/ControlBar';
import { LyricRenderer } from './components/LyricRenderer';
import { SettingsPanel } from './components/SettingsPanel';

function App() {
    const [isLocked, setIsLocked] = useState(false);
    const [isSettingsOpen, setIsSettingsOpen] = useState(false);
    const { config, setConfig, save: saveConfig, isLoaded } = useConfig();
    
    const { musicInfo, playerState } = useAimp();
    
    const { mainText, subText } = useLyrics(musicInfo?.FileName, playerState?.Position);
    
    const lyricRef = useRef<HTMLDivElement>(null);
    const resizeTimeoutRef = useRef<number | null>(null);
    const isResizingRef = useRef(false);

    useEffect(() => {
        if (!config.windowWidth) {
            setConfig({ ...config, windowWidth: window.innerWidth });
        }

        const cancel = EventsOn("lock_state_change", (locked: boolean) => {
            setIsLocked(locked);
        });

        return () => cancel();
    }, []);

    useEffect(() => {
        SetWindowClickThrough(isLocked);
    }, [isLocked]);

    const standardHeight = useMemo(() => {
        const safeMultiplier = 3.5; 
        const basePadding = 40; 
        return Math.ceil((config.fontSize * safeMultiplier) + basePadding);
    }, [config.fontSize]);

    const calculateTargetHeight = useCallback((contentHeight: number) => {
        const padding = 20; 
        return Math.ceil(Math.max(contentHeight + padding, standardHeight));
    }, [standardHeight]);

    useEffect(() => {
        const handleResize = () => {
            if (isSettingsOpen) return;
            
            isResizingRef.current = true;
            const currentW = window.innerWidth;
            const currentH = window.innerHeight;

            let targetH = standardHeight;
            if (lyricRef.current) {
                targetH = calculateTargetHeight(lyricRef.current.offsetHeight);
            }

            if (isLoaded && Math.abs(currentW - config.windowWidth) > 5) {
                if (resizeTimeoutRef.current) clearTimeout(resizeTimeoutRef.current);
                resizeTimeoutRef.current = window.setTimeout(() => {
                    const newConfig = { ...config, windowWidth: currentW };
                    setConfig(newConfig);
                    saveConfig(newConfig);
                    isResizingRef.current = false;
                }, 200);
            }

            if (Math.abs(currentH - targetH) > 5) {
                ResizeWindow(currentW, targetH);
            }
        };

        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, [isSettingsOpen, config, standardHeight, calculateTargetHeight, setConfig, saveConfig, isLoaded]);

    useLayoutEffect(() => {
        if (isSettingsOpen) {
            ResizeWindow(400, 520);
        } else {
            if (lyricRef.current) {
                const targetH = calculateTargetHeight(lyricRef.current.offsetHeight);
                const targetW = config.windowWidth || window.innerWidth;
                
                ResizeWindow(Math.ceil(targetW), Math.ceil(targetH));
            }
        }
    }, [isSettingsOpen, mainText, subText, config.fontSize, config.windowWidth, calculateTargetHeight]);

    const handleOpenSettings = useCallback(() => {
        setConfig({ ...config, windowWidth: window.innerWidth });
        setIsSettingsOpen(true);
    }, [config, setConfig]);

    const handleCloseSettings = useCallback(() => {
        saveConfig(config);
        setIsSettingsOpen(false);
    }, [config, saveConfig]);

    const currentBgOpacity = isSettingsOpen ? 0.95 : config.bgOpacity;

    return (
        <div 
            className="anim-basic w-screen h-screen overflow-hidden flex flex-col relative border border-white/10 rounded-xl shadow-2xl"
            style={{ 
                // @ts-ignore
                "--wails-draggable": isLocked ? "none" : "drag",
                backgroundColor: `rgba(0, 0, 0, ${currentBgOpacity})`,
            }}
        >
            <div className={`flex-1 flex flex-col w-full h-full ${isSettingsOpen ? 'opacity-100' : 'opacity-100'} anim-fade`}>
                {isSettingsOpen ? (
                    <SettingsPanel config={config} onChange={setConfig} onClose={handleCloseSettings} />
                ) : (
                    <>
                        {!isLocked && (
                            <ControlBar 
                                fileName={musicInfo?.FileName}
                                onOpenSettings={handleOpenSettings}
                                onLock={() => setIsLocked(true)}
                                onClose={QuitApp}
                            />
                        )}
                        <div className="flex-1 flex items-center justify-center w-full min-h-0 px-4">
                            <LyricRenderer ref={lyricRef} mainText={mainText} subText={subText} config={config} />
                        </div>
                    </>
                )}
            </div>
        </div>
    );
}

export default App;

// AILrc/frontend/src/App.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue';
import { SetWindowClickThrough, QuitApp, ResizeWindow } from "../wailsjs/go/main/App";
import { EventsOn } from "../wailsjs/runtime/runtime";
import { useAimp } from './composables/useAimp';
import { useLyrics } from './composables/useLyrics';
import { useConfig } from './composables/useConfig';
import ControlBar from './components/ControlBar.vue';
import LyricRenderer from './components/LyricRenderer.vue';
import SettingsPanel from './components/SettingsPanel.vue';

const isLocked = ref(false);
const isSettingsOpen = ref(false);

const { config, setConfig, save: saveConfig, isLoaded } = useConfig();
const { musicInfo, playerState } = useAimp();
const { mainText, subText } = useLyrics(
    computed(() => musicInfo.value?.FileName),
    computed(() => playerState.value?.Position)
);

const lyricRef = ref<InstanceType<typeof LyricRenderer>>();
const resizeTimeoutRef = ref<number | null>(null);
const isResizingRef = ref(false);

onMounted(() => {
    if (!config.value.windowWidth) {
        setConfig({ ...config.value, windowWidth: window.innerWidth });
    }

    const cancel = EventsOn('lock_state_change', (locked: boolean) => {
        isLocked.value = locked;
    });

    onUnmounted(() => cancel());
});

watch(isLocked, (locked) => {
    SetWindowClickThrough(locked);
});

const standardHeight = computed(() => {
    const safeMultiplier = 3.5;
    const basePadding = 40;
    return Math.ceil((config.value.fontSize * safeMultiplier) + basePadding);
});

const calculateTargetHeight = (contentHeight: number) => {
    const padding = 20;
    return Math.ceil(Math.max(contentHeight + padding, standardHeight.value));
};

onMounted(() => {
    const handleResize = () => {
        if (isSettingsOpen.value) return;
        
        isResizingRef.value = true;
        const currentW = window.innerWidth;
        const currentH = window.innerHeight;

        let targetH = standardHeight.value;
        if (lyricRef.value?.lyricRef) {
            targetH = calculateTargetHeight(lyricRef.value.lyricRef.offsetHeight);
        }

        if (isLoaded.value && Math.abs(currentW - config.value.windowWidth) > 5) {
            if (resizeTimeoutRef.value) clearTimeout(resizeTimeoutRef.value);
            resizeTimeoutRef.value = window.setTimeout(() => {
                const newConfig = { ...config.value, windowWidth: currentW };
                setConfig(newConfig);
                saveConfig(newConfig);
                isResizingRef.value = false;
            }, 200);
        }

        if (Math.abs(currentH - targetH) > 5) {
            ResizeWindow(currentW, targetH);
        }
    };

    window.addEventListener('resize', handleResize);
    onUnmounted(() => window.removeEventListener('resize', handleResize));
});

watch(
    [isSettingsOpen, mainText, subText, () => config.value.fontSize, () => config.value.windowWidth],
    async () => {
        await nextTick();
        
        if (isSettingsOpen.value) {
            ResizeWindow(400, 520);
        } else {
            if (lyricRef.value?.lyricRef) {
                const targetH = calculateTargetHeight(lyricRef.value.lyricRef.offsetHeight);
                const targetW = config.value.windowWidth || window.innerWidth;
                ResizeWindow(Math.ceil(targetW), Math.ceil(targetH));
            }
        }
    },
    { flush: 'post' }
);

const handleOpenSettings = () => {
    setConfig({ ...config.value, windowWidth: window.innerWidth });
    isSettingsOpen.value = true;
};

const handleCloseSettings = () => {
    saveConfig(config.value);
    isSettingsOpen.value = false;
};

const currentBgOpacity = computed(() => 
    isSettingsOpen.value ? 0.95 : config.value.bgOpacity
);
</script>

<template>
    <div 
        class="anim-basic w-screen h-screen overflow-hidden flex flex-col relative border border-white/10 rounded-xl shadow-2xl"
        :style="{ 
            '--wails-draggable': isLocked ? 'none' : 'drag',
            backgroundColor: `rgba(0, 0, 0, ${currentBgOpacity})`
        }"
    >
        <div :class="['flex-1 flex flex-col w-full h-full opacity-100 anim-fade']">
            <SettingsPanel 
                v-if="isSettingsOpen"
                :config="config"
                @change="setConfig"
                @close="handleCloseSettings"
            />
            <template v-else>
                <ControlBar 
                    v-if="!isLocked"
                    :file-name="musicInfo?.FileName"
                    @open-settings="handleOpenSettings"
                    @lock="isLocked = true"
                    @close="QuitApp"
                />
                <div class="flex-1 flex items-center justify-center w-full min-h-0 px-4">
                    <LyricRenderer 
                        ref="lyricRef"
                        :main-text="mainText"
                        :sub-text="subText"
                        :config="config"
                    />
                </div>
            </template>
        </div>
    </div>
</template>
