// AILrc/frontend/src/components/LyricRenderer.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { hexToRgba } from "../utils/color";
import type { AppConfig } from "../types";

interface Props {
    mainText: string;
    subText: string;
    config: AppConfig;
}

const props = defineProps<Props>();

const lyricRef = ref<HTMLDivElement>();

const textColor = computed(() => hexToRgba(props.config.fontColor, props.config.textOpacity));
const glowColor = computed(() => hexToRgba(props.config.strokeColor, props.config.textOpacity * 0.6));
const deepShadow = computed(() => hexToRgba(props.config.strokeColor, props.config.textOpacity * 0.9));

const mainTextStyle = computed(() => ({
    fontSize: `${props.config.fontSize}px`,
    fontWeight: 800,
    color: textColor.value,
    textShadow: `0 0 1px ${deepShadow.value}, 0 2px 4px ${glowColor.value}, 0 0 10px ${glowColor.value}`,
    fontFamily: '"Microsoft YaHei", sans-serif',
    lineHeight: '1.2',
    width: '100%'
}));

const subTextStyle = computed(() => ({
    fontSize: `${Math.max(14, props.config.fontSize * 0.55)}px`,
    fontWeight: 500,
    color: textColor.value,
    textShadow: `0 1px 2px ${deepShadow.value}`,
    fontFamily: '"Microsoft YaHei", sans-serif',
    lineHeight: '1.3',
    width: '100%',
    opacity: 0.85
}));

defineExpose({ lyricRef });
</script>

<template>
    <div
        ref="lyricRef"
        class="pointer-events-none flex flex-col items-center justify-center p-2 w-full h-auto"
    >
        <div
            class="leading-tight tracking-wide wrap-break-word whitespace-pre-wrap text-center"
            :style="mainTextStyle"
        >
            {{ mainText }}
        </div>

        <div
            v-if="subText"
            class="leading-tight tracking-wide wrap-break-word whitespace-pre-wrap text-center mt-1.5"
            :style="subTextStyle"
        >
            {{ subText }}
        </div>
    </div>
</template>

// AILrc/frontend/src/components/LyricRenderer.tsx
import { forwardRef } from 'react';
import { AppConfig } from "../types";
import { hexToRgba } from "../utils/color";

interface LyricRendererProps {
    mainText: string;
    subText: string;
    config: AppConfig;
}

export const LyricRenderer = forwardRef<HTMLDivElement, LyricRendererProps>(({ mainText, subText, config }, ref) => {
    const textColor = hexToRgba(config.fontColor, config.textOpacity);
    const glowColor = hexToRgba(config.strokeColor, config.textOpacity * 0.6);
    const deepShadow = hexToRgba(config.strokeColor, config.textOpacity * 0.9);

    return (
        <div 
            ref={ref}
            className="pointer-events-none flex flex-col items-center justify-center p-2 w-full h-auto"
        >
            <div 
                className="leading-tight tracking-wide wrap-break-word whitespace-pre-wrap text-center"
                style={{ 
                    fontSize: `${config.fontSize}px`,
                    fontWeight: 800,
                    color: textColor,
                    textShadow: `0 0 1px ${deepShadow}, 0 2px 4px ${glowColor}, 0 0 10px ${glowColor}`,
                    fontFamily: '"Microsoft YaHei", sans-serif',
                    lineHeight: '1.2',
                    width: '100%'
                }}
            >
                {mainText}
            </div>

            {subText && (
                <div 
                    className="leading-tight tracking-wide wrap-break-word whitespace-pre-wrap text-center mt-1.5"
                    style={{ 
                        fontSize: `${Math.max(14, config.fontSize * 0.55)}px`,
                        fontWeight: 500,
                        color: textColor,
                        textShadow: `0 1px 2px ${deepShadow}`,
                        fontFamily: '"Microsoft YaHei", sans-serif',
                        lineHeight: '1.3',
                        width: '100%',
                        opacity: 0.85
                    }}
                >
                    {subText}
                </div>
            )}
        </div>
    );
});
